		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title">Privacy Policy (<b style="font-weight: 600">Last modified: April, 2015</b>)</h4>
				</div>
				<div class="modal-body">
					<div class="panel-group" id="accordion2" role="tablist" aria-multiselectable="true">
						<div class="panel panel-default">
							<div class="panel-heading" role="tab" id="heading_1">
								<h4 class="panel-title" data-toggle="collapse" data-parent="#accordion2" href="#collapse_1" aria-expanded="true" aria-controls="collapse_1">
									General
								</h4>
							</div>
							<div id="collapse_1" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading_1">
								<div class="panel-body">
									<h1></h1>
									<p>
										Dinneract, Inc. ("Dinneract", "we", "our", or "us") has developed this Privacy Policy ("Policy") to explain what information we collect from our users ("users" or "you") and how we use and share this information. 
										This Policy applies to your use of our website at dinneract.com, our mobile application and any related services (the "Service").
										We may change this Policy from time to time. If we make changes, we will notify you by revising the date at the top of the policy. 
										We encourage you to review the Privacy Policy whenever you access the Services to stay informed about our information practices.
									</p>
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading" role="tab" id="heading_2">
								<h4 class="panel-title" data-toggle="collapse" data-parent="#accordion2" href="#collapse_2" aria-expanded="true" aria-controls="collapse_2">
									Information We Collect
								</h4>
							</div>
							<div id="collapse_2" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_2">
								<div class="panel-body">
									<p>
										Visitors: We collect information if you visit our website or use our Service, even if you do not register with Dinneract including: IP address, geographic location (country based on IP address), browser type, version and language setting and operating system type, version and language setting.
									</p>
									<br/>
									<p>
										Registration and Use of Service: In addition to the information above, we collect additional information when you register with our Service including: email address, password, name, user name, photo, birth date, geographic location, "about me" info and mobile device ID. We collect usage information when you use the Service such as: the posts you create or like, items you linked, items you save, the users you are following and that are following you, the groups to which you belong, and comments you post on sets or collections.
									</p>
									<br/>
									<p>
										Info through other Services: You also may give us permission to collect your information in other services. For example, you may create an account via a social networking service ("SNS") such as Facebook or Twitter or connect an SNS account to an existing Dinneract account. When you do this, it allows us to obtain information from those accounts (for example, your friends or contacts). Or you may connect your Dinneract account with a blogging service.
									</p>
									<br/>
									<p>
										Cookies: We use "cookies" in our Service to collect information. A cookie is a small data file that we transfer to your computer or mobile device's hard disk. We use cookies for two purposes. First, we utilize "persistent" cookies to save your login information for future logins to the Service. Second, we utilize "session ID" cookies to enable certain features of the Service, to better understand how you interact with the Service and to monitor aggregate usage by users and web traffic routing on the Service. Unlike persistent cookies, session cookies are deleted from your computer when you log off from the Service and then close your browser.
									</p>
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading" role="tab" id="heading_3">
								<h4 class="panel-title" data-toggle="collapse" data-parent="#accordion2" href="#collapse_3" aria-expanded="true" aria-controls="collapse_3">
									How We Use Information
								</h4>
							</div>
							<div id="collapse_3" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_3">
								<div class="panel-body">
									<p>
										We may use information about you for various purposes, including to:
									</p>
									<br/>
									<ul>
										<li>
											1. Provide and improve our Service;
										</li>
										<li>
											2. Process transactions or operate contests/sweepstakes and send you related information;
										</li>
										<li>
											3. Respond to your comments, questions and requests and provide customer service;
										</li>
										<li>
											4. Help your friends and contacts find you on Dinneract for example, through your Facebook account or email addresses;
										</li>
										<li>
											5. Send you technical notices, updates, security alerts and support and administrative messages;
										</li>
										<li>
											6. Communicate with you about products, services, offers, promotions, rewards, and events offered by Dinneract and others, and provide news and information we think will be of interest to you;
										</li>
										<li>
											7. Monitor and analyze trends, usage and activities in connection with our Service;
										</li>
										<li>
											8. Customize the Service and provide advertisements, content or features that match your interests;
										</li>
										<li>
											9. Link or combine with information we get from others to help provide you with better service;
										</li>
										<li>
											10. Detect, investigate and/or prevent fraudulent, unauthorized or illegal activity; and
										</li>
										<li>
											11. Carry out any other purpose for which the information was collected.
										</li>
									</ul>
									<br />									
									<p>
										The information we collect may be "personally identifiable" (meaning it can be used to specifically identify you as a unique person) or "non-personally identifiable" (meaning it can't be used to specifically identify you). We use both types of information, and combinations of both types, as described above.
									</p>
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading" role="tab" id="heading_4">
								<h4 class="panel-title" data-toggle="collapse" data-parent="#accordion2" href="#collapse_4" aria-expanded="true" aria-controls="collapse_4">
									Sharing Your Information
								</h4>
							</div>
							<div id="collapse_4" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_4">
								<div class="panel-body">
									<p>
										We may share personally identifiable information as follows:
									</p>
									<br/>
									<ul>
										<li>
											1. With your consent (for example, when you've chosen to link your Dinneract account to Facebook);
										</li>
										<li>
											2. With third party vendors, consultants and other service providers who need access to such information to perform work on our behalf;
										</li>
										<li>
											3. With analytics providers for the purpose of analyzing user data;
										</li>
										<li>
											4. With advertisers;
										</li>
										<li>
											5. With other users (for example, your user profile is available for anyone to see);
										</li>
										<li>
											6. When we believe that we are lawfully authorized or required to do so or that doing so is reasonably necessary or appropriate to comply with the law or legal processes or respond to lawful requests or legal authorities, including responding to lawful subpoenas, warrants or court orders;
										</li>
										<li>
											7. To enforce or apply our privacy policy, our terms of use or our other policies or agreements;
										</li>
										<li>
											8. To protect the rights, property, or safety of Dinneract, our users, or others; and
										</li>
										<li>
											9. In connection with, or during negotiations of, any merger, sale of company assets, financing or acquisition, or in any other situation where personal information may be disclosed or transferred as one of our business assets.
										</li>
									</ul>
									<br />										
									<p>
										We may also share aggregated or non-personally identifiable information with third parties.
									</p>
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading" role="tab" id="heading_5">
								<h4 class="panel-title" data-toggle="collapse" data-parent="#accordion2" href="#collapse_5" aria-expanded="true" aria-controls="collapse_5">
									Third Parties
								</h4>
							</div>
							<div id="collapse_5" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_5">
								<div class="panel-body">
									We may let other companies use cookies, web beacons, and other technologies in our Service. 
									These companies may collect information such as unique device identifiers, IP address, geo location, gender and user activity. 
									This information may be used to analyze your use of the Service. 
									In addition, some companies may use the information they collect on our Service to deliver targeted advertisements.
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading" role="tab" id="heading_6">
								<h4 class="panel-title" data-toggle="collapse" data-parent="#accordion2" href="#collapse_6" aria-expanded="true" aria-controls="collapse_6">
									Your Choices Regarding Information
								</h4>
							</div>
							<div id="collapse_6" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_6">
								<div class="panel-body">
									<p>
										Email: If you decide at any time that you no longer wish to receive email communications from us, please follow the unsubscribe instructions provided in any of the communications or update your "preferences" information in your account settings.									</p>
									<br/>
									<p>
										Cookies: You can usually instruct your browser, by changing its settings, to stop accepting cookies or to prompt you before accepting a cookie from the websites you visit. If you do not accept cookies, however, you may not be able to use all portions of the Service or all functionality of the Service.									</p>
									<br/>
									<p>
										De-Linking Account: You may de-link your Dinneract account from an account on another service such as Facebook in the "sharing" section in your account settings.
									</p>
									<br/>
									<p>
										Messages: Users may choose to restrict user messaging to only those people they are following on the Dinneract Service.
									</p>
									<br/>
									<p>
										Changing or Deleting Your Information: You may review, update, correct or delete the information in your account by contacting us or by editing your profile via the Service. If you completely delete all of your information, then your user account may become deactivated. We may retain certain information as required by law, for legitimate business purposes, or as part of our regular retention practices. We may also retain cached or archived copies of information about you.
									</p>
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading" role="tab" id="heading_7">
								<h4 class="panel-title" data-toggle="collapse" data-parent="#accordion2" href="#collapse_7" aria-expanded="true" aria-controls="collapse_7">
									Security
								</h4>
							</div>
							<div id="collapse_7" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_7">
								<div class="panel-body">
									We use commercially reasonable safeguards to preserve the integrity and security of information collected and maintained through the Service. However, we cannot ensure or warrant the security of any information you provide to us or guarantee that information on the Service may not be accessed, disclosed, altered, or destroyed by unauthorized persons.
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading" role="tab" id="heading_8">
								<h4 class="panel-title" data-toggle="collapse" data-parent="#accordion2" href="#collapse_8" aria-expanded="true" aria-controls="collapse_8">
									International Transfer
								</h4>
							</div>
							<div id="collapse_8" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_8">
								<div class="panel-body">
									Your information may be transferred to and maintained on computers located outside of your state, province, country or other governmental jurisdiction where the privacy laws may not be as protective as those in your jurisdiction. If you are located outside the United States and choose to provide information to us, Dinneract transfers personal information to the United States and processes it there. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading" role="tab" id="heading_9">
								<h4 class="panel-title" data-toggle="collapse" data-parent="#accordion2" href="#collapse_9" aria-expanded="true" aria-controls="collapse_9">
									Children
								</h4>
							</div>
							<div id="collapse_9" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_9">
								<div class="panel-body">
									The Service is not directed to children under 13. 
									We do not knowingly collect personally identifiable information from children under 13. 
									If a parent or guardian becomes aware that his or her child has provided us with personal information without their consent, 
									he or she should contact us at dinneract2015@gmail.com<!--help@dinneract.com-->.
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading" role="tab" id="heading_10">
								<h4 class="panel-title" data-toggle="collapse" data-parent="#accordion2" href="#collapse_10" aria-expanded="true" aria-controls="collapse_10">
									How to Contact Us
								</h4>
							</div>
							<div id="collapse_10" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_10">
								<div class="panel-body">
									If you have any questions about this Policy or any of the practices described herein, 
									please contact us through email at dinneract2015@gmail.com<!--help@dinneract.com-->.
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- End of Modal body -->
			</div>
			<!-- End of Modal content -->
		</div>
		<!-- End of Modal dialog -->
	